### ISSUE TITLE
仓库初始化

### ISSUE THREAD

**Issue by ghost** [netless-io/community-apps#15]
是自己从头建一个新仓库，还是从主仓库fork一个出来？

**Comment by hyrious** [comment]
是自己建，[模版仓库 (可选)](https://github.com/netless-io/community-app-template) 右上角有个 <q>Use this template</q> 点下去的效果等于自己建一个项目并复制模版仓库的所有文件。

**Comment by ghost** [comment]
但是我看模板仓库自带的readme和提交流程要求的reademe格式，差别巨大，
如果我通过模板仓库来进行操作，后面是不是要把readme全换掉？

**Comment by hyrious** [comment]
确实，提交流程要求是 @kylezhang 最近才加的，可以问问他有没有什么要求。

我们必要的信息只是一个有效的仓库地址，其他的我觉得没有那么严格。

**Comment by ghost** [comment]
感谢，这点我清楚了；
还有一个就是，作品 App 列表，是我直接在主仓库编辑，还是在我fork出来的库编辑然后Pull Request到主仓库？

**Comment by hyrious** [comment]
你没有这个仓库的权限，只能通过 PR

**Comment by ghost** [comment]
>我做了PR，但项目还是空的；你们有个叫做eric的同事过来联系说，可以后续完善，想问一下最后截止日期是哪一天？

**Comment by Leooeloel** [comment]
比赛截止今天晚上24:00

**Comment by Leooeloel** [comment]
虽然比赛今晚结束，后面也欢迎给我们贡献插件呀～

**Comment by ghost** [comment]
感谢；
